### ISSUE TITLE
Component - BdsAutocomplete

### ISSUE THREAD

**Issue by Wilkor** [takenet/blip-ds#434]
Hi guys, I'm having a problem when I try to export this component. When I try to run my application, I get the following error:

Failed to compile.

Attempted import error: 'BdsAutocomplete' is not exported from 'blip-ds/dist/blip-ds-react'.

Could you kindly help me?

**Comment by WillianLomeu** [comment]
The export of new components has been discontinued. 
Here we have documentation explaining this subject: https://design.take.net/240287753/p/216ef2-instalao/b/18ee3a

**Comment by Wilkor** [comment]
Thanks for the answer! I will consult the documentation.
